### PR TITLE
Added reverse-proxy to the Docker Deployment independent from Angular client

### PR DESCRIPTION
**Pull request by cbeldacap**
Added 3rd container to the deployment: `reverse-proxy` and changed Angular's nginx configuration.

image

### CODE REVIEW

**Comment by cbeldacap** [comment]
Solution proposal to #75

**Comment by sjimenez77** [comment]
Tested successfully using play-with-docker.com

**Comment by amarinso** [comment]
IMHO we should rename "reverse-proxy" to something more meaningful like "edge server"

**Comment by amarinso** [comment]
Also booting the edge server before the backend services results in nginx errors... this has happened when deploying to kubernetes the solution... so you have to deploy in certain order... which is not good

Either we look for a nginx solution that does not check availability of the backend when booting or change nginx for other tool... traefik comes to mind which also provides an API for dynamic configuration... may be a good solution to explore

**Comment by sjimenez77** [comment]
It makes sense for me, but many people understand already what _reverse proxy_ means and what to expect from it. I do not know if calling it _edge server_ will confuse the community. 

Traefik looks really good. What do you think @cbeldacap?

**Comment by cbeldacap** [comment]
@sjimenez77 @amarinso Well, I think both options are OK. But a container called `edge-server` may give more information as an "entrance hall" to the application rather than a "normal" reverse-proxy, which would refer to lots of things. 

Regarding the traefik-nginx thing, I would need to study deeper on it. But looks also cool at a first sight.

**Comment by andihess** [comment]
@all - If you allow me a vote: Go for three container setup with nginx as reverse proxy. It is minimal with respect to used components but still close to a setup that could be also a productive one. And "reverse proxy" is a term that everybody understands.

In addition: I think we really need to be clear what kind of demo this should be.

Case A: It is either a demo that allows to run MyThaiStar in a setup that could be also a productive one. Then it should be rather simple with respect to the infrastructure and should use components that are really widespread. You have already nginx as web server for the Angular client. Introducing another reverse proxy tool adds complexity (even if it is just inside a container) which is unneccesary for the case of "just run My Thai Star".

Case B: We make it a demo for an innovative edge server that utilizes MyThaiStar in the demo. But this is something different that should be a demo on its own. If you want to do something like this I recommend approaches that work - in the best case - even without any configuration of the reverse proxy. If you are interested I'm happy to elaborate options.

**Comment by amarinso** [comment]
Well, this just works if started on the proper order because of the problem I described that nginx fails when backends are not running.

My first option was to fix this, as I suppose is something common and for sure nginx will have a configuration for this issue.

For me, the aim of MyThaiStar is to provide a demo that can be run not only local and docker local but also on cloud without effort.

Now is the case if you go to play-with-docker and simply
1. clone repo
2. docker-compose up

and you will have the ready to serve

I would like to have this same experience in other environments such as Kubernetes, which is becoming the standard for modern runtimes (i've made another PR for this)

As for the name, reverse-proxy is obviously a term that people understand, but it does not add meaning as its role in the sample. Likewise we are not calling the angular container "http server" but that is what technically is...

I agree on taking the traefik approach to another branch, it is only one of the few options enabled by the new breed of service mesh tools...

**Pull request merged**
