### PR TITLE
Modularization: Extract batch layer code from core and added ability to toggle via profile

### PR DESCRIPTION
**Pull request by hohwille**
We are currently collaborating to integrate MTS with new database vendor. In that case batch is not working what turns out as a blocker. So far MTS seems to have very "limited" batch features.
As we have https://github.com/oasp/oasp4j/issues/611 outstanding for long I use this as a chance to propose a solution. 

Feedback and discussion is welcome.

### CODE REVIEW

**Comment by vapadwal** [comment]
Currently as mentioned that MTS has limited batch features. As seen in the batch, there are the jobs (beans-billexport.xml and beans-productimport.xml) that are not related to MTS, they are from restaurant App.

Below are some of the classes that are referred in the above xml not there in MTS
BillProcessor
BillCompositeWriter

Basically, to use Batch in MTS we need to write new Jobs altogether.

**Comment by hohwille** [comment]
> Basically, to use Batch in MTS we need to write new Jobs altogether

Sounds like we need a discussion and decision with the involved people:
* should we imporve/replace the current batch?
* should we remove batch from MTS entirely and if we want to demo our batch features we could create a new sample that is completely separated from MTS?

**Comment by hohwille** [comment]
BTW: Merging this PR should not affect all these discussions. IMHO this PR is already a step forward already as you can then switch off the batch. We still have freedom to improve or delete the batch afterwards.
So what would prevent us from merging this PR?

**Comment by hohwille** [comment]
I do not know why but something went wrong here:
> Tests in error:
  findAllDishes(io.oasp.application.mtsj.dishmanagement.logic.impl.DishmanagementTest): org/springframework/batch/core/launch/JobLauncher
  filterDishes(io.oasp.application.mtsj.dishmanagement.logic.impl.DishmanagementTest): org/springframework/batch/core/launch/JobLauncher
  orderAnOrderInviteNotExist(io.oasp.application.mtsj.ordermanagement.logic.impl.OrdermanagementTest): org/springframework/batch/core/launch/JobLauncher
  orderAnOrderWithWrongToken(io.oasp.application.mtsj.ordermanagement.logic.impl.OrdermanagementTest): org/springframework/batch/core/launch/JobLauncher
  orderAnOrderAlreadyCreated(io.oasp.application.mtsj.ordermanagement.logic.impl.OrdermanagementTest): org/springframework/batch/core/launch/JobLauncher
  orderAnOrder(io.oasp.application.mtsj.ordermanagement.logic.impl.OrdermanagementTest): org/springframework/batch/core/launch/JobLauncher
  orderAnOrderBookingNotExist(io.oasp.application.mtsj.ordermanagement.logic.impl.OrdermanagementTest): org/springframework/batch/core/launch/JobLauncher
  findImageById(io.oasp.application.mtsj.imagemanagement.logic.impl.ImagemanagementTest): org/springframework/batch/core/launch/JobLauncher

It seems the batch tests have not properly been moved from `core` to `batch`. Maybe because meanwhile other changes happened on development. Using PRs is a fine thing but having many open PRs that do not get merged in time and also not having continuous integration (travis) in place seems to be kind of suicidal. I will discuss that with Santos, etc. soon...

**Comment by hohwille** [comment]
I did a fresh clone of MTS and it is working. 
Now I have synced my fork with the original MTS as additional git remote and also the git history of both clones matches. However, in my fork the develop branch is producing the above error. As this seems to be only a local issue, you can further ignore it.
I might trace it further to understand if I am facing a git bug or what is going on here...
At least good to know that the PR was merged successfully and everything is properly working so I did not mess up anything.

**Pull request merged**
